language: en
pipeline:
- name: ConveRTTokenizer
  model_url: https://github.com/connorbrinton/polyai-models/releases/download/v1.0/model.tar.gz
- name: ConveRTFeaturizer
  model_url: https://github.com/connorbrinton/polyai-models/releases/download/v1.0/model.tar.gz
- name: CountVectorsFeaturizer
- name: CountVectorsFeaturizer
  analyzer: char_wb
  min_ngram: 1
  max_ngram: 4
- name: RegexFeaturizer
- name: LexicalSyntacticFeaturizer
- name: DIETClassifier
  epochs: 60
  scale_loss: False
  weight_sparsity: 0.3
  transformer_size: 512
  BILOU_flag: True
- name: ResponseSelector
  epochs: 50
- name: EntitySynonymMapper
policies:
- name: MemoizationPolicy
- name: TEDPolicy
  max_history: 5
  epochs: 10
- name: RulePolicy